### ISSUE TITLE
能否Hook其他进程的binder通信

### ISSUE THREAD

**Issue by fanrong1992** [iofomo/binderceptor#4]
请教一下，如果给App赋予ROOT权限，能否对其他应用进程的binder进行HOOK呢？

**Comment by iofomo** [comment]
当然可以，你有ROOT权限，那就可以在每个进程启动的时候加载这个Binder拦截的模块，这样每个进程的Binder通信你就都可以拦截了


在 2024年2月23日 ***@***.***> 写道：


请教一下，如果给App赋予ROOT权限，能否对其他应用进程的binder进行HOOK呢？

**Comment by fanrong1992** [comment]
> 你有ROOT权限，那就可以在每个进程启动的时候加载这个Binder拦截的模块，这样每个进程的Binder通信你就都可以拦截了

是需要将模块注入到目标进程中吗？

**Comment by iofomo** [comment]
是的


在 2024年2月23日 ***@***.***> 写道：


你有ROOT权限，那就可以在每个进程启动的时候加载这个Binder拦截的模块，这样每个进程的Binder通信你就都可以拦截了
是需要将模块注入到目标进程中吗？

**Comment by fanrong1992** [comment]
> 是的 在 2024年2月23日 ***@***.***> 写道： 你有ROOT权限，那就可以在每个进程启动的时候加载这个Binder拦截的模块，这样每个进程的Binder通信你就都可以拦截了 是需要将模块注入到目标进程中吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的，感谢
