### ISSUE TITLE
编译报错,能否提供一份编译好的

### ISSUE THREAD

**Issue by heckerstone** [iofomo/binderceptor#5]
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
> Configure project :app
WARNING:: DSL element 'annotationProcessorOptions.includeCompileClasspath' is obsolete.
It will be removed in version 7.0 of the Android Gradle plugin.
It does not do anything and AGP no longer includes annotation processors added on your project's compile classpath
WARNING:: Using flatDirs should be avoided because it doesn't support any meta-data formats.
Currently detected usages:
- repository flatDir used in: project ':app', project ':cmpt-mts-binderceptor'
> Task :clean UP-TO-DATE
> Task :app:clean UP-TO-DATE
> Task :cmpt-mts-binderceptor:clean UP-TO-DATE
BUILD SUCCESSFUL in 2s
3 actionable tasks: 3 up-to-date
Build jni
/bin/sh: 1: ./mk.sh: not found
Build cmpt-mts-binderceptor
/usr/bin/env: ‘bash\r’: No such file or directory
Build app
/usr/bin/env: ‘bash\r’: No such file or directory

**Comment by iofomo** [comment]
因为这是SDK，所以没有编译的版本
貌似是你的shell执行环境有问题，你是Windows平台？

**Comment by iofomo** [comment]
已经提供了一个编译好的debug版本

**Comment by heckerstone** [comment]
感谢
我在windows kaili 都没有编译成功

**Comment by heckerstone** [comment]
目前我集成了一版，可以正常使用。另外：如何伪造一个服务 必须在native层吗

**Comment by iofomo** [comment]
> 目前我集成了一版，可以正常使用。另外：如何伪造一个服务 必须在native层吗

没明白什么意思，什么是伪造一个服务

**Comment by iofomo** [comment]
> 感谢 我在windows kaili 都没有编译成功

哦，Windows的话，你的shell环境要用Cygwin才行
